#!/bin/bash

# TODO: CONNECT TO WIFI  (manually)


# install git and clone this setup script (manually))

# sudo apt update && sudo apt upgrade -y
# sudo apt install git wget
# wget https://raw.githubusercontent.com/David-Kyrat/Public-Res/refs/heads/master/syssetup


# -------- SETUP START --------

sudo apt install -y build-essential

# network tools
sudo apt install -y \
net-tools \
iproute2 \
curl \
dnsutils \
wireless-tools

# convenience tools

sudo apt install -y \
		jq \
		lsd \
		bat \
		ripgrep \
		fd-find
sudo apt install -y keychain
snap install nvim -y


# Install Ntfy

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://archive.heckel.io/apt/pubkey.txt | sudo gpg --dearmor -o /etc/apt/keyrings/archive.heckel.io.gpg
sudo apt install apt-transport-https
sudo sh -c "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/archive.heckel.io.gpg] https://archive.heckel.io/apt debian main' \
    > /etc/apt/sources.list.d/archive.heckel.io.list"  
sudo apt update
sudo apt install -y ntfy
sudo systemctl enable ntfy
sudo systemctl start ntfy


# ----- Now Setting Up remote copy paste ----&

read -p "Press Y/Yes when you've installed ntfy. (Y/N) N: quit: " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1

# !!! 5 char missing !!! 
topic="5smmqt822t7gdkan45h1r6dhfnuk5nfkd03-ubuntuserver"

bin="/home/noahl/.bin"
mkdir -p $bin

echo '#!/bin/bash' > "$bin/ntfy_listen"
echo "ntfy sub $topic 'echo \"\$m\" > ~/log.txt'" >> "$bin/ntfy_listen"
chmod u+x "$bin/ntfy_listen"
export PATH="$bin:$PATH"

# start ntfy "daemon" (nt rlly one but osef) to forward  ntfy msgs to log file (to remote copy/paste)
ntfy sub $topic 'echo "$m" > ~/log.txt' &



# ----- Securely Getting back SSH identity key --------


mkdir -p ~/.ssh
sudo chmod 700 ~/.ssh

keyname="id_ed25519_leg5pro-identity"

curl -sSLO https://raw.githubusercontent.com/David-Kyrat/Public-Res/refs/heads/master/$keyname.gpg

echo -e "\n\n >> Downloaded encrypted private key, be ready to enter passphrase."
read -p "Press any key to continue:" confirm

gpg -d $keyname.gpg > $keyname
sudo chmod 600 $keyname
ssh-keygen -y -f $keyname > $keyname.pub
sudo chmod 600 $keyname.pub

mv $keyname  ~/.ssh/$keyname
mv $keyname.pub  ~/.ssh/$keyname.pub
ln -s ~/.ssh/$keyname ~/.ssh/id_ed25519
ln -s ~/.ssh/$keyname.pub ~/.ssh/id_ed25519.pub

#eval "$(ssh-agent -s)"
#ssh-add ~/.ssh/$keyname
eval $(keychain --eval $HOME/.ssh/$keyname)


echo -e "\nTesting Validity of decrypted ssh keys for GitHub:"

ssh -T git@github.com


# ----- Download .customrc, .gitconfig and other private config files ------

read -p "Or you authenticated to github ? / Want to continue? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1


export config="$HOME/.config"
#export config2="$HOME/configit"
#rm -rf $config2 &> ./syssetuplog.git

mv $config $config.bak &> ./syssetuplog.git

git clone -b serv --depth 1 git@github.com:David-Kyrat/DotFiles.git $config

cd

ln -f $config/.customrc
ln -f $config/.gitconfig
cp $config/gacp $bin


echo -e '#=========================\n' >> .bashrc
echo 'export XDG_CONFIG_HOME=$HOME/.config' >> .bashrc
echo 'export config=$XDG_CONFIG_HOME' >> .bashrc
echo 'export customrc=$HOME/.customrc' >> .bashrc
echo 'export bashrc=$HOME/.bashrc' >> .bashrc
echo 'source $customrc' >> .bashrc


