#!/bin/bash

# TODO: CONNECT TO WIFI  (manually)


# install git and clone this setup script (manually))

# sudo apt update && sudo apt upgrade -y
# sudo apt install git wget
# wget ...


# -------- SETUP START --------

sudo apt install -y build-essential

# network tools
sudo apt install -y \
net-tools \
iproute2 \
curl \
dnsutils \
wireless-tools

# convenience tools

sudo apt install -y \
		jq \
		lsd \
		bat \
		ripgrep \
		fd

# ....
#
#
#


# Install Ntfy

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://archive.heckel.io/apt/pubkey.txt | sudo gpg --dearmor -o /etc/apt/keyrings/archive.heckel.io.gpg
sudo apt install apt-transport-https
sudo sh -c "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/archive.heckel.io.gpg] https://archive.heckel.io/apt debian main' \
    > /etc/apt/sources.list.d/archive.heckel.io.list"  
sudo apt update
sudo apt install -y ntfy
sudo systemctl enable ntfy
sudo systemctl start ntfy

# ---


# ----- Now Setting Up remote copy paste ----&-

read -p "Press Y/Yes when you've installed ntfy. (Y/N) N: quit: " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1


# !!! 5 letters are missing !!!
$topic="5smmqt822t7gdkan45h1r6dhfnuk5n-ubuntuserver"

$bin="/home/noahl/.bin"
mkdir -p $bin

echo '#!/bin/bash' > "$bin/ntfy_listen"
echo "ntfy sub $topic 'echo \"\$m\" > ~/log.txt'" >> "$bin/ntfy_listen"
chmod u+x "$bin/ntfy_listen"
export PATH="$bin:$PATH"

# start ntfy "daemon" (nt rlly one but osef) to forward  ntfy msgs to log file (to remote copy/paste)
ntfy sub $topic 'echo "$m" > ~/log.txt' &


# ----- Securely Getting back SSH identity key --------

mkdir -p ~/.ssh
echo "$(curl -sSl https://github.com/david-kyrat.keys | rg L6mR) noahl@noahmunz-leg5pro" > ~/.ssh/id_ed25519_leg5pro-identity.pub

cat ~/.ssh/id_ed25519_leg5pro-identity.pub >> ~/.ssh/authorized_keys


# ----- Download .customrc, .gitconfig and other private config files ------

read -p "Or you authenticated to github ? / Want to continue? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1


export config="$HOME/.config"
export config2="$HOME/configit"


git clone -b serv git@github.com:David-Kyrat/DotFiles.git $config2

cp $config2/.bashrc $config
cp $config2/.customrc $config
cp $config2/.gitconfig $config
cp $config2/starship.toml $config
cp $config2/.git $config -rf

cd

ln -s $config2/.bashrc
ln -s $config2/.customrc
ln -s $config2/.gitconfig
