#!/bin/bash

# TODO: CONNECT TO WIFI  (manually)


# install git and clone this setup script (manually))

# sudo apt update && sudo apt upgrade -y
# sudo apt install git wget
# wget https://raw.githubusercontent.com/David-Kyrat/Public-Res/refs/heads/master/syssetup


# -------- SETUP START --------

sudo apt install -y build-essential

# network tools
sudo apt install -y \
net-tools \
iproute2 \
curl \
dnsutils \
wireless-tools

# convenience tools

sudo apt install -y \
		jq \
		lsd \
		bat \
		ripgrep \
		fd-find
snap install nvim -y


# Install Ntfy

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://archive.heckel.io/apt/pubkey.txt | sudo gpg --dearmor -o /etc/apt/keyrings/archive.heckel.io.gpg
sudo apt install apt-transport-https
sudo sh -c "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/archive.heckel.io.gpg] https://archive.heckel.io/apt debian main' \
    > /etc/apt/sources.list.d/archive.heckel.io.list"  
sudo apt update
sudo apt install -y ntfy
sudo systemctl enable ntfy
sudo systemctl start ntfy


# ----- Now Setting Up remote copy paste ----&

read -p "Press Y/Yes when you've installed ntfy. (Y/N) N: quit: " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1

# !!! 5 char missing !!! 
topic="5smmqt822t7gdkan45h1r6dhfnuk5nfkd03-ubuntuserver"

bin="/home/noahl/.bin"
mkdir -p $bin

echo '#!/bin/bash' > "$bin/ntfy_listen"
echo "ntfy sub $topic 'echo \"\$m\" > ~/log.txt'" >> "$bin/ntfy_listen"
chmod u+x "$bin/ntfy_listen"
export PATH="$bin:$PATH"

# start ntfy "daemon" (nt rlly one but osef) to forward  ntfy msgs to log file (to remote copy/paste)
ntfy sub $topic 'echo "$m" > ~/log.txt' &



# ----- Securely Getting back SSH identity key --------


mkdir -p ~/.ssh
sudo chmod 700 ~/.ssh

keyname="id_ed25519_leg5pro-identity"

curl -sSLO https://raw.githubusercontent.com/David-Kyrat/Public-Res/refs/heads/master/$keyname.gpg

echo -e "\n\n >> Downloaded encrypted private key, be ready to enter passphrase."
read -p "Press any key to continue:" confirm

gpg -d $keyname.gpg > $keyname
sudo chmod 600 $keyname
ssh-keygen -y -f ~/.ssh/$keyname > $keyname.pub
sudo chmod 600 $keyname.pub

mv $keyname  ~/.ssh/$keyname
mv $keyname.pub  ~/.ssh/$keyname.pub


eval "$(ssh-agent -s)"
ssh-add ~/.ssh/$keyname

echo -e "\nTesting Validity of decrypted ssh keys for GitHub:"

ssh -T git@github.com

# ! no need to download pub key since it can be fenerated from pvt key !

# --------

#echo "$(curl -sSl https://github.com/david-kyrat.keys | rg L6mR) noahl@noahmunz-leg5pro" > ~/.ssh/id_ed25519_leg5pro-identity.pub

# key=$(curl -sSl "https://github.com/david-kyrat.keys" | rg L6mR | awk '{print $2}'  | rg L6mR)
#
#
# keyname="id_ed25519_leg5pro-identity"
#
#
# if [ ! -z "$key" ]; then
# 		curl -sSl "https://github.com/david-kyrat.keys" | rg "$key" > "~/.ssh/$keyname.pub"
# 		cat ~/.ssh/$keyname.pub >> ~/.ssh/authorized_keys
# fi
#
# curl -sSLO https://raw.githubusercontent.com/David-Kyrat/Public-Res/refs/heads/master/$keyname.gpg
#
# echo -e "\n\n >> Downloaded encrypted private key, be ready to enter passphrase."
# read -p "Press any key to continue:" confirm
#
# # small name mismatch indeed
# gpg -d $keyname.gpg > ~/.ssh/$keyname
# chmod 400 ~/.ssh/$keyname



# ----- Download .customrc, .gitconfig and other private config files ------


read -p "Or you authenticated to github ? / Want to continue? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1


export config="$HOME/.config"
export config2="$HOME/configit"


git clone -b serv git@github.com:David-Kyrat/DotFiles.git $config2

cp $config2/.bashrc $config
cp $config2/.customrc $config
cp $config2/.gitconfig $config
cp $config2/starship.toml $config
cp $config2/.git $config -rf

cd

ln -s $config2/.bashrc
ln -s $config2/.customrc
ln -s $config2/.gitconfig
